import type { Proposal } from './types';

export const mockProposals: Proposal[] = [
  {
    proposalId: '1',
    title: 'Community Garden Funding',
    description: 'Proposal to allocate $5,000 from community treasury for establishing a community garden in the central park area. This will provide fresh produce and a gathering space for residents.',
    createdByUserId: 'user1',
    createdAt: '2024-01-15T10:00:00Z',
    status: 'active',
    votingDeadline: '2024-01-22T23:59:59Z',
    yesVotes: 45,
    noVotes: 12,
    abstainVotes: 3,
  },
  {
    proposalId: '2',
    title: 'Monthly Community Events',
    description: 'Establish a monthly community event series featuring local artists, food vendors, and activities. Budget: $2,000 per event.',
    createdByUserId: 'user2',
    createdAt: '2024-01-14T14:30:00Z',
    status: 'active',
    votingDeadline: '2024-01-21T23:59:59Z',
    yesVotes: 67,
    noVotes: 8,
    abstainVotes: 5,
  },
  {
    proposalId: '3',
    title: 'Neighborhood Watch Program',
    description: 'Create a neighborhood watch program with dedicated coordinators and communication channels to improve community safety.',
    createdByUserId: 'user3',
    createdAt: '2024-01-13T09:15:00Z',
    status: 'active',
    votingDeadline: '2024-01-20T23:59:59Z',
    yesVotes: 89,
    noVotes: 4,
    abstainVotes: 2,
  },
  {
    proposalId: '4',
    title: 'Community Library Expansion',
    description: 'Expand the community library with new books, digital resources, and extended hours. Total budget: $8,000.',
    createdByUserId: 'user1',
    createdAt: '2024-01-10T16:45:00Z',
    status: 'closed',
    votingDeadline: '2024-01-17T23:59:59Z',
    yesVotes: 102,
    noVotes: 15,
    abstainVotes: 8,
  },
];
